<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KecamatansSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $kecamatanList = [
            'Bakongan',
            'Kluet Utara',
            'Kluet Selatan',
            'Labuhanhaji',
            'Meukek',
            'Samadua',
            'Sawang',
            'Tapaktuan',
            'Trumon',
            'Pasi Raja',
            'Labuhan Haji Timur',
            'Labuhan Haji Barat',
            'Kluet Tengah',
            'Kluet Timur',
            'Bakongan Timur',
            'Trumon Timur',
            'Kota Bahagia',
            'Trumon Tengah',
            'Lawe Alas',
            'Lawe Sigala-Gala',
            'Bambel',
            'Babussalam',
            'Badar',
            'Babul Makmur',
            'Darul Hasanah',
            'Lawe Bulan',
            'Bukit Tusam',
            'Semadam',
            'Babul Rahmah',
            'Ketambe',
            'Deleng Pokhkisen',
            'Lawe Sumur',
            'Tanoh Alas',
            'Leuser',
            'Darul Aman',
            'Julok',
            'Idi Rayeuk',
            'Birem Bayeun',
            'Serbajadi',
            'Nurussalam',
            'Peureulak',
            'Rantau Selamat',
            'Simpang Ulim',
            'Ranto Peureulak',
            'Pante Bidari',
            'Madat',
            'Indra Makmu',
            'Idi Tunong',
            'Banda Alam',
            'Peudawa',
            'Peureulak Timur',
            'Peureulak Barat',
            'Sungai Raya',
            'Simpang Jernih',
            'Darul Ihsan',
            'Darul Falah',
            'Idi Timur',
            'Peunaron',
            'Linge',
            'Silih Nara',
            'Bebesen',
            'Pegasing',
            'Bintang',
            'Ketol',
            'Kebayakan',
            'Kute Panang',
            'Celala',
            'Laut Tawar',
            'Atu Lintang',
            'Jagong Jeget',
            'Bies',
            'Rusip Antara',
            'Johan Pahlawan',
            'Kaway XVI',
            'Sungai Mas',
            'Woyla',
            'Samatiga',
            'Bubon',
            'Arongan Lambalek',
            'Pante Ceureumen',
            'Meureubo',
            'Woyla Barat',
            'Woyla Timur',
            'Panton Reu',
            'Lhoong',
            'Lhoknga',
            'Indrapuri',
            'Seulimeum',
            'Montasik',
            'Sukamakmur',
            'Darul Imarah',
            'Peukan Bada',
            'Mesjid Raya',
            'Ingin Jaya',
            'Kuta Baro',
            'Darussalam',
            'Pulo Aceh',
            'Lembah Seulawah',
            'Kota Jantho',
            'Kuta Cot Glie',
            'Kuta Malaka',
            'Simpang Tiga',
            'Darul Kamal',
            'Baitussalam',
            'Krueng Barona Jaya',
            'Leupung',
            'Blang Bintang',
            'Batee',
            'Delima',
            'Geumpang',
            'Glumpang Tiga',
            'Indrajaya',
            'Kembang Tanjong',
            'Kota Sigli',
            'Mila',
            'Muara Tiga',
            'Mutiara',
            'Padang Tiji',
            'Peukan Baro',
            'Pidie',
            'Sakti',
            'Simpang Tiga',
            'Tangse',
            'Tiro/Truseb',
            'Keumala',
            'Mutiara Timur',
            'Grong-grong',
            'Mane',
            'Glumpang Baro',
            'Titeue',
            'Baktiya',
            'Dewantara',
            'Kuta Makmur',
            'Lhoksukon',
            'Matangkuli',
            'Muara Batu',
            'Meurah Mulia',
            'Samudera',
            'Seunuddon',
            'Syamtalira Aron',
            'Syamtalira Bayu',
            'Tanah Luas',
            'Tanah Pasir',
            'T. Jambo Aye',
            'Sawang',
            'Nisam',
            'Cot Girek',
            'Langkahan',
            'Baktiya Barat',
            'Paya Bakong',
            'Nibong',
            'Simpang Kramat',
            'Lapang',
            'Pirak Timur',
            'Geuredong Pase',
            'Banda Baro',
            'Nisam Antara',
            'Simeulue Tengah',
            'Salang',
            'Teupah Barat',
            'Simeulue Timur',
            'Teluk Dalam',
            'Simeulue Barat',
            'Teupah Selatan',
            'Alafan',
            'Teupah Tengah',
            'Simeulue Cut',
            'Pulau Banyak',
            'Simpang Kanan',
            'Singkil',
            'Gunung Meriah',
            'Kota Baharu',
            'Singkil Utara',
            'Danau Paris',
            'Suro Makmur',
            'Singkohor',
            'Kuala Baru',
            'Pulau Banyak Barat',
            'Samalanga',
            'Jeunieb',
            'Peudada',
            'Jeumpa',
            'Peusangan',
            'Makmur',
            'Gandapura',
            'Pandrah',
            'Juli',
            'Jangka',
            'Simpang Mamplam',
            'Peulimbang',
            'Kota Juang',
            'Kuala',
            'Peusangan Siblah Krueng',
            'Peusangan Selatan',
            'Kuta Blang',
            'Blangpidie',
            'Tangan-Tangan',
            'Manggeng',
            'Susoh',
            'Kuala Batee',
            'Babah Rot',
            'Setia',
            'Jeumpa',
            'Lembah Sabil',
            'Blangkejeren',
            'Kutapanjang',
            'Rikit Gaib',
            'Terangun',
            'Pining',
            'Blangpegayon',
            'Puteri Betung',
            'Dabun Gelang',
            'Blangjerango',
            'Teripe Jaya',
            'Pantan Cuaca',
            'Teunom',
            'Krueng Sabee',
            'Setia Bakti',
            'Sampoi Niet',
            'Jaya',
            'Panga',
            'Indra Jaya',
            'Darul Hikmah',
            'Pasie Raya',
            'Kuala',
            'Seunagan',
            'Seunagan Timur',
            'Beutong',
            'Darul Makmur',
            'Suka Makmue',
            'Kuala Pesisir',
            'Tadu Raya',
            'Tripa Makmur',
            'Beutong Ateuh Banggalang',
            'Manyak Payed',
            'Bendahara',
            'Karang Baru',
            'Seruway',
            'Kota Kualasinpang',
            'Kejuruan Muda',
            'Tamiang Hulu',
            'Rantau',
            'Banda Mulia',
            'Bandar Pusaka',
            'Tenggulun',
            'Sekerak',
            'Pintu Rime Gayo',
            'Permata',
            'Syiah Utama',
            'Bandar',
            'Bukit',
            'Wih Pesam',
            'Timang gajah',
            'Bener Kelipah',
            'Mesidah',
            'Gajah Putih',
            'Meureudu',
            'Ulim',
            'Jangka Buaya',
            'Bandar Dua',
            'Meurah Dua',
            'Bandar Baru',
            'Panteraja',
            'Trienggadeng',
            'Baiturrahman',
            'Kuta Alam',
            'Meuraxa',
            'Syiah Kuala',
            'Lueng Bata',
            'Kuta Raja',
            'Banda Raya',
            'Jaya Baru',
            'Ulee Kareng',
            'Sukakarya',
            'Sukajaya',
            'Sukamakmue',
            'Muara Dua',
            'Banda Sakti',
            'Blang Mangat',
            'Muara Satu',
            'Langsa Timur',
            'Langsa Barat',
            'Langsa Kota',
            'Langsa Lama',
            'Langsa Baro',
            'Simpang Kiri',
            'Penanggalan',
            'Rundeng',
            'Sultan Daulat',
            'Longkib',
            'Barus',
            'Sorkam',
            'Pandan',
            'Pinangsori',
            'Manduamas',
            'Kolang',
            'Tapian Nauli',
            'Sibabangun',
            'Sosorgadong',
            'Sorkam Barat',
            'Sirandorung',
            'Andam Dewi',
            'Sitahuis',
            'Tukka',
            'Badiri',
            'Pasaribu Tobing',
            'Barus Utara',
            'Suka Bangun',
            'Lumut',
            'Sarudik',
            'Tarutung',
            'Siatas Barita',
            'Adian Koting',
            'Sipoholon',
            'Pahae Julu',
            'Pahae Jae',
            'Simangumban',
            'Purba Tua',
            'Siborong-Borong',
            'Pagaran',
            'Parmonangan',
            'Sipahutar',
            'Pangaribuan',
            'Garoga',
            'Muara',
            'Angkola Barat',
            'Batang Toru',
            'Angkola Timur',
            'Sipirok',
            'Saipar Dolok Hole',
            'Angkola Selatan',
            'Batang Angkola',
            'Arse',
            'Marancar',
            'Sayur Matinggi',
            'Aek Bilah',
            'Muara Batang Toru',
            'Tano Tombangan Angkola',
            'Angkola Sangkunur',
            'Angkola Muara Tais',
            'Hiliduho',
            'Gido',
            'Idanogawo',
            'Bawolato',
            'Hiliserangkai',
            'Botomuzoi',
            'Ulugawo',
            // 'Ma''u',
            'Somolo-molo',
            // 'Sogae''adu',
            'Bahorok',
            'Salapian',
            'Kuala',
            'Sei Bingai',
            'Binjai',
            'Selesai',
            'Stabat',
            'Wampu',
            'Secanggang',
            'Hinai',
            'Tanjung Pura',
            'Padang Tualang',
            'Gebang',
            'Babalan',
            'Pangkalan Susu',
            'Besitang',
            'Sei Lepan',
            'Berandan Barat',
            'Batang Serangan',
            'Sawit Seberang',
            'Sirapit',
            'Kutambaru',
            'Pematang Jaya',
            'Kabanjahe',
            'Berastagi',
            'Barusjahe',
            'Tigapanah',
            'Merek',
            'Munte',
            'Juhar',
            'Tigabinanga',
            'Laubaleng',
            'Mardingding',
            'Payung',
            'Simpang Empat',
            'Kutabuluh',
            'Dolat Rayat',
            'Merdeka',
            'Naman Teran',
            'Tiganderket',
            'Gunung Meriah',
            'Tanjung Morawa',
            'Sibolangit',
            'Kutalimbaru',
            'Pancur Batu',
            'Namo Rambe',
            'Biru-Biru',
            'STM Hilir',
            'Bangun Purba',
            'Galang',
            'STM Hulu',
            'Patumbak',
            'Deli Tua',
            'Sunggal',
            'Hamparan Perak',
            'Labuhan Deli',
            'Percut Sei Tuan',
            'Batang Kuis',
            'Lubuk Pakam',
            'Pagar Merbau',
            'Pantai Labu',
            'Beringin',
            'Siantar',
            'Gunung Malela',
            'Gunung Maligas',
            'Panei',
            'Panombeian Panei',
            'Jorlang Hataran',
            'Raya Kahean',
            'Bosar Maligas',
            'Sidamanik',
            'Pamatang Sidamanik',
            'Tanah Jawa',
            'Hatonduhan',
            'Dolok Panribuan',
            'Purba',
            'Haranggaol Horisan',
            'Girsang Sipangan Bolon',
            'Dolok Batu Nanggar',
            'Huta Bayu Raja',
            'Jawa Maraja Bah Jambi',
            'Dolok Pardamean',
            'Pematang Bandar',
            'Bandar Huluan',
            'Bandar',
            'Bandar Masilam',
            'Silimakuta',
            'Dolok Silou',
            'Silou Kahean',
            'Tapian Dolok',
            'Raya',
            'Ujung Padang',
            'Pamatang Silima Huta',
            'Dolog Masagal',
            'Meranti',
            'Air Joman',
            'Tanjung Balai',
            'Sei Kepayang',
            'Simpang Empat',
            'Air Batu',
            'Pulau Rakyat',
            'Bandar Pulau',
            'Buntu Pane',
            'Bandar Pasir Mandoge',
            'Aek Kuasan',
            'Kota Kisaran Barat',
            'Kota Kisaran Timur',
            'Aek Songsongan',
            'Rahunig',
            'Sei Dadap',
            'Sei Kepayang Barat',
            'Sei Kepayang Timur',
            'Tinggi Raja',
            'Setia Janji',
            'Silau Laut',
            'Rawang Panca Arga',
            'Pulo Bandring',
            'Teluk Dalam',
            'Aek Ledong',
            'Rantau Utara',
            'Rantau Selatan',
            'Bilah Barat',
            'Bilah Hilir',
            'Bilah Hulu',
            'Pangkatan',
            'Panai Tengah',
            'Panai Hilir',
            'Panai Hulu',
            'Sidikalang',
            'Sumbul',
            'Tigalingga',
            'Siempat Nempu',
            'Silima Pungga Pungga',
            'Tanah Pinem',
            'Siempat Nempu Hulu',
            'Siempat Nempu Hilir',
            'Pegagan Hilir',
            'Parbuluan',
            'Lae Parira',
            'Gunung Sitember',
            'Berampu',
            'Silahisabungan',
            'Sitinjo',
            'Balige',
            'Laguboti',
            'Silaen',
            'Habinsaran',
            'Pintu Pohan Meranti',
            'Borbor',
            'Porsea',
            'Ajibata',
            'Lumban Julu',
            'Uluan',
            'Sigumpar',
            'Siantar Narumonda',
            'Nassau',
            'Tampahan',
            'Bonatua Lunasi',
            'Parmaksian',
            'Panyabungan',
            'Panyabungan Utara',
            'Panyabungan Timur',
            'Panyabungan Selatan',
            'Panyabungan Barat',
            'Siabu',
            'Bukit Malintang',
            'Kotanopan',
            'Lembah Sorik Marapi',
            'Tambangan',
            'Ulu Pungkut',
            'Muara Sipongi',
            'Batang Natal',
            'Lingga Bayu',
            'Batahan',
            'Natal',
            'Muara Batang Gadis',
            'Ranto Baek',
            'Huta Bargot',
            'Puncak Sorik Marapi',
            'Pakantan',
            'Sinunukan',
            'Naga Juang',
            'Lolomatua',
            'Gomo',
            'Lahusa',
            'Hibala',
            'Pulau-Pulau Batu',
            'Teluk Dalam',
            'Amandraya',
            'Lolowau',
            'Susua',
            'Maniamolo',
            'Hilimegai',
            'Toma',
            'Mazino',
            'Umbunasi',
            'Aramo',
            'Pulau-Pulau Batu Timur',
            'Mazo',
            'Fanayama',
            'Ulunoyo',
            'Huruna',
            // 'O''o''u',
            'Onohazumba',
            // 'Hilisalawa''ahe',
            'Ulususua',
            //'Sidua''ori',
            'Somambawa',
            'Boronadu',
            'Simuk',
            'Pulau-Pulau Batu Barat',
            'Pulau-Pulau Batu Utara',
            'Tanah Masa',
            'Luahagundre Maniamolo',
            'Onolalu',
            'Ulu Idanotae',
            'Idanotae',
            'Sitelu Tali Urang Jehe',
            'Kerajaan',
            'Salak',
            'Sitelu Tali Urang Julu',
            'Pergetteng Getteng Sengkut',
            'Pagindar',
            'Tinada',
            'Siempat Rube',
            'Parlilitan',
            'Pollung',
            'Baktiraja',
            'Paranginan',
            'Lintong Nihuta',
            'Dolok Sanggul',
            'Sijamapolang',
            'Onan Ganjang',
            'Pakkat',
            'Tarabintang',
            'Simanindo',
            'Onan Runggu',
            'Nainggolan',
            'Palipi',
            'Harian',
            'Sianjar Mula Mula',
            'Ronggur Nihuta',
            'Pangururan',
            'Sitio-tio',
            'Pantai Cermin',
            'Perbaungan',
            'Teluk Mengkudu',
            'Sei Rampah',
            'Tanjung Beringin',
            'Bandar Khalipah',
            'Dolok Merawan',
            'Sipispis',
            'Dolok Masihul',
            'Kotarih',
            'Silinda',
            'Serba Jadi',
            'Tebing Tinggi',
            'Pegajahan',
            'Sei Bamban',
            'Tebing Syahbandar',
            'Bintang Bayu',
            'Medang Deras',
            'Sei Suka',
            'Air Putih',
            'Lima Puluh',
            'Talawi',
            'Tanjung Tiram',
            'Sei Balai',
            'Laut Tador',
            'Lima Puluh Pesisir',
            'Datuk Lima Puluh',
            'Datuk Tanah Datar',
            'Nibung Hangus',
            'Dolok Sigompulon',
            'Dolok',
            'Halongonan',
            'Padang Bolak',
            'Padang Bolak Julu',
            'Portibi',
            'Batang Onang',
            'Simangambat',
            'Hulu Sihapas',
            'Padang Bolak Tenggara',
            'Halongonan Timur',
            'Ujung Batu',
            'Sosopan',
            'Barumun Tengah',
            'Huristak',
            'Lubuk Barumun',
            'Huta Raja Tinggi',
            'Ulu Barumun',
            'Barumun',
            'Sosa',
            'Batang Lubu Sutam',
            'Barumun Selatan',
            'Aek Nabara Barumun',
            'Sihapas Barumun',
            'Barumun Baru',
            'Ulu Sosa',
            'Sosa Julu',
            'Barumun Barat',
            'Sosa Timur',
            'Kotapinang',
            'Kampung Rakyat',
            'Torgamba',
            'Sungai Kanan',
            'Silangkitang',
            'Kualuh Hulu',
            'Kualuh Leidong',
            'Kualuh Hilir',
            'Aek Kuo',
            'Marbau',
            'Na IX - X',
            'Aek Natas',
            'Kualuh Selatan',
            'Lotu',
            'Sawo',
            'Tuhemberua',
            'Sitolu Ori',
            'Namohalu Esiwa',
            'Alasa Talumuzoi',
            'Alasa',
            'Tugala Oyo',
            'Afulu',
            'Lahewa',
            'Lahewa Timur',
            'Lahomi',
            'Sirombu',
            'Mandrehe Barat',
            // 'Moro''o',
            'Mandrehe',
            'Mandrehe Utara',
            'Lolofitu Moi',
            // 'Ulu Moro''o',
            'Medan Kota',
            'Medan Sunggal',
            'Medan Helvetia',
            'Medan Denai',
            'Medan Barat',
            'Medan Deli',
            'Medan Tuntungan',
            'Medan Belawan',
            'Medan Amplas',
            'Medan Area',
            'Medan Johor',
            'Medan Marelan',
            'Medan Labuhan',
            'Medan Tembung',
            'Medan Maimun',
            'Medan Polonia',
            'Medan Baru',
            'Medan Perjuangan',
            'Medan Petisah',
            'Medan Timur',
            'Medan Selayang',
            'Siantar Timur',
            'Siantar Barat',
            'Siantar Utara',
            'Siantar Selatan',
            'Siantar Marihat',
            'Siantar Martoba',
            'Siantar Sitalasari',
            'Siantar Marimbun',
            'Sibolga Utara',
            'Sibolga Kota',
            'Sibolga Selatan',
            'Sibolga Sambas',
            'Tanjungbalai Selatan',
            'Tanjungbalai Utara',
            'Sei Tualang Raso',
            'Teluk Nibung',
            'Datuk Bandar',
            'Datuk Bandar Timur',
            'Binjai Utara',
            'Binjai Kota',
            'Binjai Barat',
            'Binjai Timur',
            'Binjai Selatan',
            'Padang Hulu',
            'Rambutan',
            'Padang Hilir',
            'Bajenis',
            'Tebing Tinggi Kota',
            'Padangsidimpuan Utara',
            'Padangsidimpuan Selatan',
            'Padangsidimpuan Batunadua',
            'Padangsidimpuan Hutaimbaru',
            'Padangsidimpuan Tenggara',
            'Padangsidimpuan Angkola Julu',
            'Gunungsitoli',
            'Gunungsitoli Selatan',
            'Gunungsitoli Utara',
            'Gunungsitoli Idanoi',
            // 'Gunungsitoli Alo''oa',
            'Gunungsitoli Barat',
            'Pancung Soal',
            'Ranah Pesisir',
            'Lengayang',
            'Batang Kapas',
            'IV Jurai',
            'Bayang',
            'Koto XI Tarusan',
            'Sutera',
            'Linggo Sari Baganti',
            'Lunang',
            'Basa Ampek Balai Tapan',
            'IV Nagari Bayang Utara',
            'Airpura',
            'Ranah Ampek Hulu Tapan',
            'Silaut',
            'Pantai Cermin',
            'Lembah Gumanti',
            'Payung Sekaki',
            'Lembang Jaya',
            'Gunung Talang',
            'Bukit Sundi',
            'IX Koto Sungai Lasi',
            'Kubung',
            'X Koto Singkarak',
            'X Koto Diatas',
            'Junjung Sirih',
            'Hiliran Gumanti',
            'Tigo Lurah',
            'Danau Kembar',
            'Tanjung Gadang',
            'Sijunjung',
            'IV Nagari',
            'Kamang Baru',
            'Lubuak Tarok',
            'Koto VII',
            'Sumpur Kudus',
            'Kupitan',
            'X Koto',
            'Batipuh',
            'Rambatan',
            'Lima Kaum',
            'Tanjung Emas',
            'Lintau Buo',
            'Sungayang',
            'Sungai Tarab',
            'Pariangan',
            'Salimpaung',
            'Padang Ganting',
            'Tanjuang Baru',
            'Lintau Buo Utara',
            'Batipuah Selatan',
            'Lubuk Alung',
            'Batang Anai',
            'Nan Sabaris',
            '2 x 11 Enam Lingkuang',
            'VII Koto Sungai Sarik',
            'V Koto Kampung Dalam',
            'Sungai Garingging',
            'Sungai Limau',
            'IV Koto Aur Malintang',
            'Ulakan Tapakih',
            'Sintuak Toboh Gadang',
            'Padang Sago',
            'Batang Gasan',
            'V Koto Timur',
            '2 x 11 Kayu Tanam',
            'Patamuan',
            'Enam Lingkung',
            'Tanjung Mutiara',
            'Lubuk Basung',
            'Tanjung Raya',
            'Matur',
            'IV Koto',
            'Banuhampu',
            'Ampek Angkek',
            'Baso',
            'Tilatang Kamang',
            'Palupuh',
            'Palembayan',
            'Sungai Pua',
            'Ampek Nagari',
            'Candung',
            'Kamang Magek',
            'Malalak',
            'Suliki',
            'Guguak',
            'Payakumbuh',
            'Luak',
            'Harau',
            'Pangkalan Koto Baru',
            'Kapur IX',
            'Gunuang Omeh',
            'Lareh Sago Halaban',
            'Situjuah Limo Nagari',
            'Mungka',
            'Bukik Barisan',
            'Akabiluru',
            'Bonjol',
            'Lubuk Sikaping',
            'Panti',
            'Mapat Tunggul',
            'Duo Koto',
            'Tigo Nagari',
            'Rao',
            'Mapat Tunggul Selatan',
            'Simpang Alahan Mati',
            'Padang Gelugur',
            'Rao Utara',
            'Rao Selatan',
            'Pagai Utara',
            'Sipora Selatan',
            'Siberut Selatan',
            'Siberut Utara',
            'Siberut Barat',
            'Siberut Barat Daya',
            'Siberut Tengah',
            'Sipora Utara',
            'Sikakap',
            'Pagai Selatan',
            'Koto Baru',
            'Pulau Punjung',
            'Sungai Rumbai',
            'Sitiung',
            'Sembilan Koto',
            'Timpeh',
            'Koto Salak',
            'Tiumang',
            'Padang Laweh',
            'Asam Jujuhan',
            'Koto Besar',
            'Sangir',
            'Sungai Pagu',
            'Koto Parik Gadang Diateh',
            'Sangir Jujuan',
            'Sangir Batang Hari',
            'Pauh Duo',
            'Sangir Balai Janggo',
            'Sungaiberemas',
            'Lembah Melintang',
            'Pasaman',
            'Talamau',
            'Kinali',
            'Gunungtuleh',
            'Ranah Batahan',
            'Koto Balingka',
            'Sungaiaur',
            'Luhak Nan Duo',
            'Sasak Ranah Pesisir',
            'Padang Selatan',
            'Padang Timur',
            'Padang Barat',
            'Padang Utara',
            'Bungus Teluk Kabung',
            'Lubuk Begalung',
            'Lubuk Kilangan',
            'Pauh',
            'Kuranji',
            'Nanggalo',
            'Koto Tangah',
            'Lubuk Sikarah',
            'Tanjung Harapan',
            'Lembah Segar',
            'Barangin',
            'Silungkang',
            'Talawi',
            'Padang Panjang Timur',
            'Padang Panjang Barat',
            'Guguak Panjang',
            'Mandiangin Koto Selayan',
            'Aur Birugo Tigo Baleh',
            'Payakumbuh Barat',
            'Payakumbuh Utara',
            'Payakumbuh Timur',
            'Lamposi Tigo Nagori',
            'Payakumbuh Selatan',
            'Pariaman Tengah',
            'Pariaman Utara',
            'Pariaman Selatan',
            'Pariaman Timur',
            'Bangkinang Kota',
            'Kampar',
            'Tambang',
            'XIII Koto Kampar',
            'Kuok',
            'Siak Hulu',
            'Kampar Kiri',
            'Kampar Kiri Hilir',
            'Kampar Kiri Hulu',
            'Tapung',
            'Tapung Hilir',
            'Tapung Hulu',
            'Salo',
            'Rumbio Jaya',
            'Bangkinang',
            'Perhentian Raja',
            'Kampa',
            'Kampar Utara',
            'Kampar Kiri Tengah',
            'Gunung Sahilan',
            'Koto Kampar Hulu',
            'Rengat',
            'Rengat Barat',
            'Kelayang',
            'Pasir Penyu',
            'Peranap',
            'Siberida',
            'Batang Cenaku',
            'Batang Gangsal',
            'Lirik',
            'Kuala Cenaku',
            'Sungai Lala',
            'Lubuk Batu Jaya',
            'Rakit Kulim',
            'Batang Peranap',
            'Bengkalis',
            'Bantan',
            'Bukit Batu',
            'Mandau',
            'Rupat',
            'Rupat Utara',
            'Siak Kecil',
            'Pinggir',
            'Bandar Laksamana',
            'Talang Muandau',
            'Bathin Solapan',
            'Reteh',
            'Enok',
            'Kuala Indragiri',
            'Tembilahan',
            'Tempuling',
            'Gaung Anak Serka',
            'Mandah',
            'Kateman',
            'Keritang',
            'Tanah Merah',
            'Batang Tuaka',
            'Gaung',
            'Tembilahan Hulu',
            'Kemuning',
            'Pelangiran',
            'Teluk Belengkong',
            'Pulau Burung',
            'Concong',
            'Kempas',
            'Sungai Batang',
            'Ukui',
            'Pangkalan Kerinci',
            'Pangkalan Kuras',
            'Pangkalan Lesung',
            'Langgam',
            'Pelalawan',
            'Kerumutan',
            'Bunut',
            'Teluk Meranti',
            'Kuala Kampar',
            'Bandar Sei Kijang',
            'Bandar Petalangan',
            'Ujung Batu',
            'Rokan IV Koto',
            'Rambah',
            'Tambusai',
            'Kepenuhan',
            'Kunto Darussalam',
            'Rambah Samo',
            'Rambah Hilir',
            'Tambusai Utara',
            'Bangun Purba',
            'Tandun',
            'Kabun',
            'Bonai Darussalam',
            'Pagaran Tapah Darussalam',
            'Kepenuhan Hulu',
            'Pendalian IV Koto',
            'Kubu',
            'Bangko',
            'Tanah Putih',
            'Rimba Melintang',
            'Bagan Sinembah',
            'Pasir Limau Kapas',
            'Sinaboi',
            'Pujud',
            'Tanah Putih Tanjung Melawan',
            'Bangko Pusako',
            'Simpang Kanan',
            'Batu Hampar',
            'Rantau Kopar',
            'Pekaitan',
            'Kubu Babussalam',
            'Tanjung Medan',
            'Bagan Sinembah Raya',
            'Balai Jaya',
            'Siak',
            'Sungai Apit',
            'Minas',
            'Tualang',
            'Sungai Mandau',
            'Dayun',
            'Kerinci Kanan',
            'Bunga Raya',
            'Koto Gasib',
            'Kandis',
            'Lubuk Dalam',
            'Sabak Auh',
            'Mempura',
            'Pusako',
            'Kuantan Mudik',
            'Kuantan Tengah',
            'Singingi',
            'Kuantan Hilir',
            'Cerenti',
            'Benai',
            'Gunungtoar',
            'Singingi Hilir',
            'Pangean',
            'Logas Tanah Darat',
            'Inuman',
            'Hulu Kuantan',
            'Kuantan Hilir Seberang',
            'Sentajo Raya',
            'Pucuk Rantau',
            'Tebing Tinggi',
            'Rangsang Barat',
            'Rangsang',
            'Tebing Tinggi Barat',
            'Merbau',
            'Pulaumerbau',
            'Tebing Tinggi Timur',
            'Tasik Putri Puyu',
            'Rangsang Pesisir',
            'Sukajadi',
            'Pekanbaru Kota',
            'Sail',
            'Lima Puluh',
            'Senapelan',
            'Rumbai Barat',
            'Bukit Raya',
            'Binawidya',
            'Marpoyan Damai',
            'Tenayan Raya',
            'Payung Sekaki',
            'Rumbai',
            'Tuahmadani',
            'Kulim',
            'Rumbai Timur',
            'Dumai Barat',
            'Dumai Timur',
            'Bukit Kapur',
            'Sungai Sembilan',
            'Medang Kampai',
            'Dumai Kota',
            'Dumai Selatan',
            'Gunung Raya',
            'Danau Kerinci',
            'Sitinjau Laut',
            'Air Hangat',
            'Gunung Kerinci',
            'Batang Merangin',
            'Keliling Danau',
            'Kayu Aro',
            'Air Hangat Timur',
            'Gunung Tujuh',
            'Siulak',
            'Depati Tujuh',
            'Siulak Mukai',
            'Kayu Aro Barat',
            'Bukitkerman',
            'Air Hangat Barat',
            'Tanah Cogok',
            'Danau Kerinci Barat',
            'Jangkat',
            'Bangko',
            'Muara Siau',
            'Sungai Manau',
            'Tabir',
            'Pamenang',
            'Tabir Ulu',
            'Tabir Selatan',
            'Lembah Masurai',
            'Bangko Barat',
            'Nalo Tantan',
            'Batang Masumai',
            'Pamenang Barat',
            'Tabir Ilir',
            'Tabir Timur',
            'Renah Pembarap',
            'Pangkalan Jambu',
            'Jangkat Timur',
            'Renah Pamenang',
            'Pamenang Selatan',
            'Margo Tabir',
            'Tabir Lintas',
            'Tabir Barat',
            'Tiang Pumpung',
            'Batang Asai',
            'Limun',
            'Sarolangun',
            'Pauh',
            'Pelawan',
            'Mandiangin',
            'Air Hitam',
            'Bathin VIII',
            'Singkut',
            'Cermin Nan Gedang',
            'Mandiangin Timur',
            'Mersam',
            'Muara Tembesi',
            'Muara Bulian',
            'Batin XXIV',
            'Pemayung',
            'Maro Sebo Ulu',
            'Bajubang',
            'Maro Sebo Ilir',
            'Jambi Luar Kota',
            'Sekernan',
            'Kumpeh',
            'Maro Sebo',
            'Mestong',
            'Kumpeh Ulu',
            'Sungai Bahar',
            'Sungai Gelam',
            'Bahar Utara',
            'Bahar Selatan',
            'Taman Rajo',
            'Tungkal Ulu',
            'Tungkal Ilir',
            'Pengabuan',
            'Betara',
            'Merlung',
            'Tebing Tinggi',
            'Batang Asam',
            'Renah Mendaluh',
            'Muara Papalik',
            'Seberang Kota',
            'Bram Itam',
            'Kuala Betara',
            'Senyerang',
            'Muara Sabak Timur',
            'Nipah Panjang',
            'Mendahara',
            'Rantau Rasau',
            'S a d u',
            'Dendang',
            'Muara Sabak Barat',
            'Kuala Jambi',
            'Mendahara Ulu',
            'Geragai',
            'Berbak',
            'Tanah Tumbuh',
            'Rantau Pandan',
            'Pasar Muaro Bungo',
            'Jujuhan',
            'Tanah Sepenggal',
            'Pelepat',
            'Limbur Lubuk Mengkuang',
            'Muko-muko Bathin VII',
            'Pelepat Ilir',
            'Batin II Babeko',
            'Bathin III',
            'Bungo Dani',
            'Rimbo Tengah',
            'Bathin III Ulu',
            'Bathin II Pelayang',
            'Jujuhan Ilir',
            'Tanah Sepenggal Lintas',
            'Tebo Tengah',
            'Tebo Ilir',
            'Tebo Ulu',
            'Rimbo Bujang',
            'Sumay',
            'VII Koto',
            'Rimbo Ulu',
            'Rimbo Ilir',
            'Tengah Ilir',
            'Serai Serumpun',
            'VII Koto Ilir',
            'Muara Tabir',
            'Telanaipura',
            'Jambi Selatan',
            'Jambi Timur',
            'Pasar Jambi',
            'Pelayangan',
            'Danau Teluk',
            'Kota Baru',
            'Jelutung',
            'Alam Barajo',
            'Danau Sipin',
            'Paal Merah',
            'Sungai Penuh',
            'Pesisir Bukit',
            'Hamparan Rawang',
            'Tanah Kampung',
            'Kumun Debai',
            'Pondok Tinggi',
            'Koto Baru',
            'Sungai Bungkal',
            'Sosoh Buay Rayap',
            'Pengandonan',
            'Peninjauan',
            'Baturaja Barat',
            'Baturaja Timur',
            'Ulu Ogan',
            'Semidang Aji',
            'Lubuk Batang',
            'Lengkiti',
            'Sinar Peninjauan',
            'Lubuk Raja',
            'Muara Jaya',
            'Kedaton Peninjauan Raya',
            'Tanjung Lubuk',
            'Pedamaran',
            'Mesuji',
            'Kayu Agung',
            'Sirah Pulau Padang',
            'Tulung Selapan',
            'Pampangan',
            'Lempuing',
            'Air Sugihan',
            'Sungai Menang',
            'Jejawi',
            'Cengal',
            'Pangkalan Lampam',
            'Mesuji Makmur',
            'Mesuji Raya',
            'Lempuing Jaya',
            'Teluk Gelam',
            'Pedamaran Timur',
            'Tanjung Agung',
            'Muara Enim',
            'Rambang Niru',
            'Gunung Megang',
            'Gelumbang',
            'Lawang Kidul',
            'Semende Darat Laut',
            'Semende Darat Tengah',
            'Semende Darat Ulu',
            'Ujan Mas',
            'Lubai',
            'Rambang',
            'Sungai Rotan',
            'Lembak',
            'Benakat',
            'Kelekar',
            'Muara Belida',
            'Belimbing',
            'Belida Darat',
            'Lubai Ulu',
            'Empat Petulai Dangku',
            'Panang Enim',
            'Tanjungsakti Pumu',
            'Jarai',
            'Kota Agung',
            'Pulaupinang',
            'Merapi Barat',
            'Lahat',
            'Pajar Bulan',
            'Mulak Ulu',
            'Kikim Selatan',
            'Kikim Timur',
            'Kikim Tengah',
            'Kikim Barat',
            'Pseksu',
            'Gumay Talang',
            'Pagar Gunung',
            'Merapi Timur',
            'Tanjung Sakti Pumi',
            'Gumay Ulu',
            'Merapi Selatan',
            'Tanjungtebat',
            'Muarapayang',
            'Sukamerindu',
            'Mulak Sebingkai',
            'Lahat Selatan',
            'Tugumulyo',
            'Muara Lakitan',
            'Muara Kelingi',
            'Jayaloka',
            'Muara Beliti',
            'STL Ulu Terawas',
            'Selangit',
            'Megang Sakti',
            'Purwodadi',
            'BTS. Ulu',
            'Tiang Pumpung Kepungut',
            'Sumber Harta',
            'Tuah Negeri',
            'Suka Karya',
            'Sekayu',
            'Lais',
            'Sungai Keruh',
            'Batang Hari Leko',
            'Sanga Desa',
            'Babat Toman',
            'Sungai Lilin',
            'Keluang',
            'Bayung Lencir',
            'Plakat Tinggi',
            'Lalan',
            'Tungkal Jaya',
            'Lawang Wetan',
            'Babat Supat',
            'Jirak Jaya',
            'Banyuasin I',
            'Banyuasin II',
            'Banyuasin III',
            'Pulau Rimau',
            'Betung',
            'Rambutan',
            'Muara Padang',
            'Muara Telang',
            'Makarti Jaya',
            'Talang Kelapa',
            'Rantau Bayur',
            'Tanjung Lago',
            'Muara Sugihan',
            'Air Salek',
            'Tungkal Ilir',
            'Suak Tapeh',
            'Sembawa',
            'Sumber Marga Telang',
            'Air Kumbang',
            'Karangagung Ilir',
            'Selat Panuguan',
            'Martapura',
            'Buay Madang',
            'Belitang',
            'Cempaka',
            'Buay Pemuka Peliung',
            'Madang Suku II',
            'Madang Suku I',
            'Semendawai Suku III',
            'Belitang II',
            'Belitang III',
            'Bunga Mayang',
            'Buay Madang Timur',
            'Madang Suku III',
            'Semendawai Barat',
            'Semendawai Timur',
            'Jayapura',
            'Belitang Jaya',
            'Belitang Madang Raya',
            'Belitang Mulya',
            'Buay Pemuka Bangsa Raja',
            'Muara Dua',
            'Pulau Beringin',
            'Banding Agung',
            'Muara Dua Kisam',
            'Simpang',
            'Buay Sandang Aji',
            'Buay Runjung',
            'Mekakau Ilir',
            'Buay Pemaca',
            'Kisam Tinggi',
            'Kisam Ilir',
            'Buay Pematang Ribu Ranau Tengah',
            'Warkuk Ranau Selatan',
            'Runjung Agung',
            'Sungai Are',
            'Sindang Danau',
            'Buana Pemaca',
            'Tiga Dihaji',
            'Buay Rawan',
            'Muara Kuang',
            'Tanjung Batu',
            'Tanjung Raja',
            'Indralaya',
            'Pemulutan',
            'Rantau Alai',
            'Indralaya Utara',
            'Indralaya Selatan',
            'Pemulutan Selatan',
            'Pemulutan Barat',
            'Rantau Panjang',
            'Sungai Pinang',
            'Kandis',
            'Rambang Kuang',
            'Lubuk Keliat',
            'Payaraman',
            'Muara Pinang',
            'Pendopo',
            'Ulu Musi',
            'Tebing Tinggi',
            'Lintang Kanan',
            'Talang Padang',
            'Pasemah Air Keruh',
            'Sikap Dalam',
            'Saling',
            'Pendopo Barat',
            'Talang Ubi',
            'Penukal Utara',
            'Penukal',
            'Abab',
            'Tanah Abang',
            'Rupit',
            'Rawas Ulu',
            'Nibung',
            'Rawas Ilir',
            'Karang Dapo',
            'Karang Jaya',
            'Ulu Rawas',
            'Ilir Barat II',
            'Seberang Ulu I',
            'Seberang Ulu II',
            'Ilir Barat I',
            'Ilir Timur I',
            'Ilir Timur II',
            'Sukarami',
            'Sako',
            'Kemuning',
            'Kalidoni',
            'Bukit Kecil',
            'Gandus',
            'Kertapati',
            'Plaju',
            'Alang-alang Lebar',
            'Sematang Borang',
            'Jakabaring',
            'Ilir Timur Tiga',
            'Pagar Alam Utara',
            'Pagar Alam Selatan',
            'Dempo Utara',
            'Dempo Selatan',
            'Dempo Tengah',
            'Lubuk Linggau Timur I',
            'Lubuk Linggau Barat I',
            'Lubuk Linggau Selatan I',
            'Lubuk Linggau Utara I',
            'Lubuk Linggau Timur II',
            'Lubuk Linggau Barat II',
            'Lubuk Linggau Selatan II',
            'Lubuk Linggau Utara II',
            'Prabumulih Barat',
            'Prabumulih Timur',
            'Cambai',
            'Rambang Kapak Tengah',
            'Prabumulih Utara',
            'Prabumulih Selatan',
            'Kedurang',
            'Seginim',
            'Pino',
            'Manna',
            'Kota Manna',
            'Pino Raya',
            'Kedurang Ilir',
            'Air Nipis',
            'Ulu Manna',
            'Bunga Mas',
            'Pasar Manna',
            'Kota Padang',
            'Padang Ulak Tanding',
            'Sindang Kelingi',
            'Curup',
            'Bermani Ulu',
            'Selupu Rejang',
            'Curup Utara',
            'Curup Timur',
            'Curup Selatan',
            'Curup Tengah',
            'Binduriang',
            'Sindang Beliti Ulu',
            'Sindang Dataran',
            'Sindang Beliti Ilir',
            'Bermani Ulu Raya',
            'Enggano',
            'Kerkap',
            'Kota Arga Makmur',
            'Giri Mulya',
            'Padang Jaya',
            'Lais',
            'Batik Nau',
            'Ketahun',
            'Napal Putih',
            'Putri Hijau',
            'Air Besi',
            'Air Napal',
            'Hulu Palik',
            'Air Padang',
            'Arma Jaya',
            'Tanjung Agung Palik',
            'Ulok Kupai',
            'Pinang Raya',
            'Marga Sakti Sebelat',
            'Kinal',
            'Tanjung Kemuning',
            'Kaur Utara',
            'Kaur Tengah',
            'Kaur Selatan',
            'Maje',
            'Nasal',
            'Semidang Gumay',
            'Kelam Tengah',
            'Luas',
            'Muara Sahung',
            'Tetap',
            'Lungkang Kule',
            'Padang Guci Hilir',
            'Padang Guci Hulu',
            'Sukaraja',
            'Seluma',
            'Talo',
            'Semidang Alas',
            'Semidang Alas Maras',
            'Air Periukan',
            'Lubuk Sandi',
            'Seluma Barat',
            'Seluma Timur',
            'Seluma Utara',
            'Seluma Selatan',
            'Talo Kecil',
            'Ulu Talo',
            'Ilir Talo',
            'Lubuk Pinang',
            'Kota Mukomuko',
            'Teras Terunjam',
            'Pondok Suguh',
            'Ipuh',
            'Malin Deman',
            'Air Rami',
            'Teramang Jaya',
            'Selagan Raya',
            'Penarik',
            'XIV Koto',
            'V Koto',
            'Air Majunto',
            'Air Dikit',
            'Sungai Rumbai',
            'Lebong Utara',
            'Lebong Atas',
            'Lebong Tengah',
            'Lebong Selatan',
            'Rimbo Pengadang',
            'Topos',
            'Bingin Kuning',
            'Lebong Sakti',
            'Pelabai',
            'Amen',
            'Uram Jaya',
            'Pinang Belapis',
            'Bermani Ilir',
            'Ujan Mas',
            'Tebat Karai',
            'Kepahiang',
            'Merigi',
            'Kebawetan',
            'Seberang Musi',
            'Muara Kemumu',
            'Karang Tinggi',
            'Talang Empat',
            'Pondok Kelapa',
            'Pematang Tiga',
            'Pagar Jati',
            'Taba Penanjung',
            'Merigi Kelindang',
            'Merigi Sakti',
            'Pondok Kubang',
            'Bang Haji',
            'Semidang Lagan',
            'Selebar',
            'Gading Cempaka',
            'Teluk Segara',
            'Muara Bangka Hulu',
            'Kampung Melayu',
            'Ratu Agung',
            'Ratu Samban',
            'Sungai Serut',
            'Singaran Pati',
            'Natar',
            'Tanjung Bintang',
            'Kalianda',
            'Sidomulyo',
            'Katibung',
            'Penengahan',
            'Palas',
            'Jati Agung',
            'Ketapang',
            'Sragi',
            'Raja Basa',
            'Candipuro',
            'Merbau Mataram',
            'Bakauheni',
            'Tanjung Sari',
            'Way Sulan',
            'Way Panji',
            'Kalirejo',
            'Bangun Rejo',
            'Padang Ratu',
            'Gunung Sugih',
            'Trimurjo',
            'Punggur',
            'Terbanggi Besar',
            'Seputih Raman',
            'Rumbia',
            'Seputih Banyak',
            'Seputih Mataram',
            'Seputih Surabaya',
            'Terusan Nunyai',
            'Bumi Ratu Nuban',
            'Bekri',
            'Seputih Agung',
            'Way Pangubuan',
            'Bandar Mataram',
            'Pubian',
            'Selagai Lingga',
            'Anak Tuha',
            'Sendang Agung',
            'Kota Gajah',
            'Bumi Nabung',
            'Way Seputih',
            'Bandar Surabaya',
            'Anak Ratu Aji',
            'Putra Rumbia',
            'Bukit Kemuning',
            'Kotabumi',
            'Sungkai Selatan',
            'Tanjung Raja',
            'Abung Timur',
            'Abung Barat',
            'Abung Selatan',
            'Sungkai Utara',
            'Kotabumi Utara',
            'Kotabumi Selatan',
            'Abung Tengah',
            'Abung Tinggi',
            'Abung Semuli',
            'Abung Surakarta',
            'Muara Sungkai',
            'Bunga Mayang',
            'Hulu Sungkai',
            'Sungkai Tengah',
            'Abung Pekurun',
            'Sungkai Jaya',
            'Sungkai Barat',
            'Abung Kunang',
            'Blambangan Pagar',
            'Balik Bukit',
            'Sumber Jaya',
            'Belalau',
            'Way Tenong',
            'Sekincau',
            'Suoh',
            'Batu Brak',
            'Sukau',
            'Gedung Surian',
            'Kebun Tebu',
            'Air Hitam',
            'Pagar Dewa',
            'Batu Ketulis',
            'Lumbok Seminung',
            'Bandar Negeri Suoh',
            'Menggala',
            'Gedung Aji',
            'Banjar Agung',
            'Gedung Meneng',
            'Rawa Jitu Selatan',
            'Penawar Tama',
            'Rawa Jitu Timur',
            'Banjar Margo',
            'Rawa Pitu',
            'Penawar Aji',
            'Dente Teladas',
            'Meraksa Aji',
            'Gedung Aji Baru',
            'Banjar Baru',
            'Menggala Timur',
            'Kota Agung',
            'Talang Padang',
            'Wonosobo',
            'Pulau Panggung',
            'Cukuh Balak',
            'Pugung',
            'Semaka',
            'Sumberejo',
            'Ulu Belu',
            'Pematang Sawa',
            'Kelumbayan',
            'Kota Agung Barat',
            'Kota Agung Timur',
            'Gisting',
            'Gunung Alip',
            'Limau',
            'Bandar Negeri Semuong',
            'Air Naningan',
            'Bulok',
            'Klumbayan Barat',
            'Sukadana',
            'Labuhan Maringgai',
            'Jabung',
            'Pekalongan',
            'Sekampung',
            'Batanghari',
            'Way Jepara',
            'Purbolinggo',
            'Raman Utara',
            'Metro Kibang',
            'Marga Tiga',
            'Sekampung Udik',
            'Batanghari Nuban',
            'Bumi Agung',
            'Bandar Sribhawono',
            'Mataram Baru',
            'Melinting',
            'Gunung Pelindung',
            'Pasir Sakti',
            'Waway Karya',
            'Labuhan Ratu',
            'Braja Selebah',
            'Way Bungur',
            'Marga Sekampung',
            'Blambangan Umpu',
            'Kasui',
            'Banjit',
            'Baradatu',
            'Bahuga',
            'Pakuan Ratu',
            'Negeri Agung',
            'Way Tuba',
            'Rebang Tangkas',
            'Gunung Labuhan',
            'Negara Batin',
            'Negeri Besar',
            'Buay Bahuga',
            'Bumi Agung',
            'Umpu Semenguk',
            'Gedong Tataan',
            'Negeri Katon',
            'Tegineneng',
            'Way Lima',
            'Padang Cermin',
            'Punduh Pidada',
            'Kedondong',
            'Marga Punduh',
            'Way Khilau',
            'Teluk Pandan',
            'Way Ratai',
            'Pringsewu',
            'Gading Rejo',
            'Ambarawa',
            'Pardasuka',
            'Pagelaran',
            'Banyumas',
            'Adiluwih',
            'Sukoharjo',
            'Pagelaran Utara',
            'Mesuji',
            'Mesuji Timur',
            'Rawa Jitu Utara',
            'Way Serdang',
            'Simpang Pematang',
            'Panca Jaya',
            'Tanjung Raya',
            'Tulang Bawang Tengah',
            'Tumijajar',
            'Tulang Bawang Udik',
            'Gunung Terang',
            'Gunung Agung',
            'Way Kenanga',
            'Lambu Kibang',
            'Pagar Dewa',
            'Batu Putih',
            'Pesisir Tengah',
            'Pesisir Selatan',
            'Lemong',
            'Pesisir Utara',
            'Karya Penggawa',
            'Pulaupisang',
            'Way Krui',
            'Krui Selatan',
            'Ngambur',
            'Ngaras',
            'Bangkunat',
            'Kedaton',
            'Sukarame',
            'Tanjungkarang Barat',
            'Panjang',
            'Tanjungkarang Timur',
            'Tanjungkarang Pusat',
            'Telukbetung Selatan',
            'Telukbetung Barat',
            'Telukbetung Utara',
            'Rajabasa',
            'Tanjung Senang',
            'Sukabumi',
            'Kemiling',
            'Labuhan Ratu',
            'Way Halim',
            'Langkapura',
            'Enggal',
            'Kedamaian',
            'Telukbetung Timur',
            'Bumi Waras',
            'Metro Pusat',
            'Metro Utara',
            'Metro Barat',
            'Metro Timur',
            'Metro Selatan',
            'Sungailiat',
            'Belinyu',
            'Merawang',
            'Mendo Barat',
            'Pemali',
            'Bakam',
            'Riau Silip',
            'Puding Besar',
            'Tanjung Pandan',
            'Membalong',
            'Selat Nasik',
            'Sijuk',
            'Badau',
            'Toboali',
            'Lepar',
            'Airgegas',
            'Simpang Rimba',
            'Payung',
            'Tukak Sadai',
            'Pulaubesar',
            'Kepulauan Pongok',
            'Koba',
            'Pangkalan Baru',
            'Sungai Selan',
            'Simpang Katis',
            'Namang',
            'Lubuk Besar',
            'Mentok',
            'Simpang Teritip',
            'Jebus',
            'Kelapa',
            'Tempilang',
            'Parittiga',
            'Manggar',
            'Gantung',
            'Dendang',
            'Kelapa Kampit',
            'Damar',
            'Simpang Renggiang',
            'Simpang Pesak',
            'Bukit Intan',
            'Taman Sari',
            'Pangkal Balam',
            'Rangkui',
            'Gerunggang',
            'Gabek',
            'Girimaya',
            'Gunung Kijang',
            'Bintan Timur',
            'Bintan Utara',
            'Teluk Bintan',
            'Tambelan',
            'Telok Sebong',
            'Toapaya',
            'Mantang',
            'Bintan Pesisir',
            'Seri Kuala Lobam',
            'Moro',
            'Kundur',
            'Karimun',
            'Meral',
            'Tebing',
            'Buru',
            'Kundur Utara',
            'Kundur Barat',
            'Durai',
            'Meral Barat',
            'Ungar',
            'Belat',
            'Selat Gelam',
            'Sugie Besar',
            'Midai',
            'Bunguran Barat',
            'Serasan',
            'Bunguran Timur',
            'Bunguran Utara',
            'Subi',
            'Pulau Laut',
            'Pulau Tiga',
            'Bunguran Timur Laut',
            'Bunguran Tengah',
            'Bunguran Selatan',
            'Serasan Timur',
            'Bunguran Batubi',
            'Pulau Tiga Barat',
            'Suak Midai',
            'Pulau Panjang',
            'Pulau Seluan',
            'Singkep',
            'Lingga',
            'Senayang',
            'Singkep Barat',
            'Lingga Utara',
            'Singkep Pesisir',
            'Lingga Timur',
            'Selayar',
            'Singkep Selatan',
            'Kepulauan Posek',
            'Katang Bidare',
            'Temiang Pesisir',
            'Bakung Serumpun',
            'Siantan',
            'Palmatak',
            'Siantan Timur',
            'Siantan Selatan',
            'Jemaja Timur',
            'Jemaja',
            'Siantan Tengah',
            'Siantan Utara',
            'Jemaja Barat',
            'Kute Siantan',
            'Belakang Padang',
            'Batu Ampar',
            'Sekupang',
            'Nongsa',
            'Bulang',
            'Lubuk Baja',
            'Sei Beduk',
            'Galang',
            'Bengkong',
            'Batam Kota',
            'Sagulung',
            'Batu Aji',
            'Tanjung Pinang Barat',
            'Tanjung Pinang Timur',
            'Tanjung Pinang Kota',
            'Bukit Bestari',
            'Kepulauan Seribu Utara',
            'Kepulauan Seribu Selatan.',
            'Gambir',
            'Sawah Besar',
            'Kemayoran',
            'Senen',
            'Cempaka Putih',
            'Menteng',
            'Tanah Abang',
            'Johar Baru',
            'Penjaringan',
            'Tanjung Priok',
            'Koja',
            'Cilincing',
            'Pademangan',
            'Kelapa Gading',
            'Cengkareng',
            'Grogol Petamburan',
            'Taman Sari',
            'Tambora',
            'Kebon Jeruk',
            'Kalideres',
            'Pal Merah',
            'Kembangan',
            'Tebet',
            'Setiabudi',
            'Mampang Prapatan',
            'Pasar Minggu',
            'Kebayoran Lama',
            'Cilandak',
            'Kebayoran Baru',
            'Pancoran',
            'Jagakarsa',
            'Pesanggrahan',
            'Matraman',
            'Pulogadung',
            'Jatinegara',
            'Kramatjati',
            'Pasar Rebo',
            'Cakung',
            'Duren Sawit',
            'Makasar',
            'Ciracas',
            'Cipayung',
            'Cibinong',
            'Gunung Putri',
            'Citeureup',
            'Sukaraja',
            'Babakan Madang',
            'Jonggol',
            'Cileungsi',
            'Cariu',
            'Sukamakmur',
            'Parung',
            'Gunung Sindur',
            'Kemang',
            'Bojong Gede',
            'Leuwiliang',
            'Ciampea',
            'Cibungbulang',
            'Pamijahan',
            'Rumpin',
            'Jasinga',
            'Parung Panjang',
            'Nanggung',
            'Cigudeg',
            'Tenjo',
            'Ciawi',
            'Cisarua',
            'Megamendung',
            'Caringin',
            'Cijeruk',
            'Ciomas',
            'Dramaga',
            'Tamansari',
            'Klapanunggal',
            'Ciseeng',
            'Ranca Bungur',
            'Sukajaya',
            'Tanjungsari',
            'Tajurhalang',
            'Cigombong',
            'Leuwisadeng',
            'Tenjolaya',
            'Palabuhanratu',
            'Simpenan',
            'Cikakak',
            'Bantargadung',
            'Cisolok',
            'Cikidang',
            'Lengkong',
            'Jampangtengah',
            'Warungkiara',
            'Cikembar',
            'Cibadak',
            'Nagrak',
            'Parungkuda',
            'Bojonggenteng',
            'Parakansalak',
            'Cicurug',
            'Cidahu',
            'Kalapanunggal',
            'Kabandungan',
            'Waluran',
            'Jampangkulon',
            'Ciemas',
            'Kalibunder',
            'Surade',
            'Cibitung',
            'Ciracap',
            'Gunungguruh',
            'Cicantayan',
            'Cisaat',
            'Kadudampit',
            'Caringin',
            'Sukabumi',
            'Sukaraja',
            'Kebonpedes',
            'Cireunghas',
            'Sukalarang',
            'Pabuaran',
            'Purabaya',
            'Nyalindung',
            'Gegerbitung',
            'Sagaranten',
            'Curugkembar',
            'Cidolog',
            'Cidadap',
            'Tegalbuleud',
            'Cimanggu',
            'Ciambar',
            'Cianjur',
            'Warungkondang',
            'Cibeber',
            'Cilaku',
            'Ciranjang',
            'Bojongpicung',
            'Karangtengah',
            'Mande',
            'Sukaluyu',
            'Pacet',
            'Cugenang',
            'Cikalongkulon',
            'Sukaresmi',
            'Sukanagara',
            'Campaka',
            'Takokak',
            'Kadupandak',
            'Pagelaran',
            'Tanggeung',
            'Cibinong',
            'Sindangbarang',
            'Agrabinta',
            'Cidaun',
            'Naringgul',
            'Campakamulya',
            'Cikadu',
            'Gekbrong',
            'Cipanas',
            'Cijati',
            'Leles',
            'Haurwangi',
            'Pasirkuda',
            'Cileunyi',
            'Cimenyan',
            'Cilengkrang',
            'Bojongsoang',
            'Margahayu',
            'Margaasih',
            'Katapang',
            'Dayeuhkolot',
            'Banjaran',
            'Pameungpeuk',
            'Pangalengan',
            'Arjasari',
            'Cimaung',
            'Cicalengka',
            'Nagreg',
            'Cikancung',
            'Rancaekek',
            'Ciparay',
            'Pacet',
            'Kertasari',
            'Baleendah',
            'Majalaya',
            'Solokanjeruk',
            'Paseh',
            'Ibun',
            'Soreang',
            'Pasirjambu',
            'Ciwidey',
            'Rancabali',
            'Cangkuang',
            'Kutawaringin',
            'Garut Kota',
            'Karangpawitan',
            'Wanaraja',
            'Tarogong Kaler',
            'Tarogong Kidul',
            'Banyuresmi',
            'Samarang',
            'Pasirwangi',
            'Leles',
            'Kadungora',
            'Leuwigoong',
            'Cibatu',
            'Kersamanah',
            'Malangbong',
            'Sukawening',
            'Karangtengah',
            'Bayongbong',
            'Cigedug',
            'Cilawu',
            'Cisurupan',
            'Sukaresmi',
            'Cikajang',
            'Banjarwangi',
            'Singajaya',
            'Cihurip',
            'Peundeuy',
            'Pameungpeuk',
            'Cisompet',
            'Cibalong',
            'Cikelet',
            'Bungbulang',
            'Mekarmukti',
            'Pakenjeng',
            'Pamulihan',
            'Cisewu',
            'Caringin',
            'Talegong',
            'Limbangan',
            'Selaawi',
            'Cibiuk',
            'Pangatikan',
            'Sucinaraja',
            'Cipatujah',
            'Karangnunggal',
            'Cikalong',
            'Pancatengah',
            'Cikatomas',
            'Cibalong',
            'Parungponteng',
            'Bantarkalong',
            'Bojongasih',
            'Culamega',
            'Bojonggambir',
            'Sodonghilir',
            'Taraju',
            'Salawu',
            'Puspahiang',
            'Tanjungjaya',
            'Sukaraja',
            'Salopa',
            'Jatiwaras',
            'Cineam',
            'Karangjaya',
            'Manonjaya',
            'Gunungtanjung',
            'Singaparna',
            'Mangunreja',
            'Sukarame',
            'Cigalontang',
            'Leuwisari',
            'Padakembang',
            'Sariwangi',
            'Sukaratu',
            'Cisayong',
            'Sukahening',
            'Rajapolah',
            'Jamanis',
            'Ciawi',
            'Kadipaten',
            'Pagerageung',
            'Sukaresik',
            'Ciamis',
            'Cikoneng',
            'Cijeungjing',
            'Sadananya',
            'Cidolog',
            'Cihaurbeuti',
            'Panumbangan',
            'Panjalu',
            'Kawali',
            'Panawangan',
            'Cipaku',
            'Jatinagara',
            'Rajadesa',
            'Sukadana',
            'Rancah',
            'Tambaksari',
            'Lakbok',
            'Banjarsari',
            'Pamarican',
            'Cimaragas',
            'Cisaga',
            'Sindangkasih',
            'Baregbeg',
            'Sukamantri',
            'Lumbung',
            'Purwadadi',
            'Banjaranyar',
            'Kadugede',
            'Ciniru',
            'Subang',
            'Ciwaru',
            'Cibingbin',
            'Luragung',
            'Lebakwangi',
            'Garawangi',
            'Kuningan',
            'Ciawigebang',
            'Cidahu',
            'Jalaksana',
            'Cilimus',
            'Mandirancan',
            'Selajambe',
            'Kramatmulya',
            'Darma',
            'Cigugur',
            'Pasawahan',
            'Nusaherang',
            'Cipicung',
            'Pancalang',
            'Japara',
            'Cimahi',
            'Cilebak',
            'Hantara',
            'Kalimanggis',
            'Cibeureum',
            'Karang Kancana',
            'Maleber',
            'Sindang Agung',
            'Cigandamekar',
            'Waled',
            'Ciledug',
            'Losari',
            'Pabedilan',
            'Babakan',
            'Karangsembung',
            'Lemahabang',
            'Susukan Lebak',
            'Sedong',
            'Astanajapura',
            'Pangenan',
            'Mundu',
            'Beber',
            'Talun',
            'Sumber',
            'Dukupuntang',
            'Palimanan',
            'Plumbon',
            'Weru',
            'Kedawung',
            'Gunung Jati',
            'Kapetakan',
            'Klangenan',
            'Arjawinangun',
            'Panguragan',
            'Ciwaringin',
            'Susukan',
            'Gegesik',
            'Kaliwedi',
            'Gebang',
            'Depok',
            'Pasaleman',
            'Pabuaran',
            'Karangwareng',
            'Tengah Tani',
            'Plered',
            'Gempol',
            'Greged',
            'Suranenggala',
            'Jamblang',
            'Lemahsugih',
            'Bantarujeg',
            'Cikijing',
            'Talaga',
            'Argapura',
            'Maja',
            'Majalengka',
            'Sukahaji',
            'Rajagaluh',
            'Leuwimunding',
            'Jatiwangi',
            'Dawuan',
            'Kadipaten',
            'Kertajati',
        ];

        $data = [];

        foreach ($kecamatanList as $index => $nama) {
            $data[] = [
                'id_kecamatan' => $index + 1, // atau kamu bisa hapus ini jika auto increment
                'nama_kecamatan' => $nama,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        DB::table('kecamatans')->insert($data);
    }
}
