<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KotaKabupatensSeeder extends Seeder
{
    public function run()
    {
        $kotaKabList = [
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KAB. ACEH BARAT',
                'kecamatan' => [
                    'Arongan Lambalek',
                    'Bubon',
                    'Johan Pahlawan',
                    'Kaway XVI',
                    'Meureubo',
                    'Pante Ceureumen',
                    'Panton Reu',
                    'Samatiga',
                    'Sungai Mas',
                    'Woyla',
                    'Woyla Barat',
                    'Woyla Timur',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KAB. ACEH BARAT DAYA',
                'kecamatan' => [
                    'Babah Rot',
                    'Jeumpa',
                    'Kuala Batee',
                    'Lembah Sabil',
                    'Manggeng',
                    'Setia',
                    'Susoh',
                    'Tangan-Tangan',
                    'Blangpidie',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KAB. ACEH BESAR',
                'kecamatan' => [
                    'Baitussalam',
                    'Blang Bintang',
                    'Darul Imarah',
                    'Darul Kamal',
                    'Darussalam',
                    'Indrapuri',
                    'Ingin Jaya',
                    'Kota Cot Glie',
                    'Kota Jantho',
                    'Krueng Barona Jaya',
                    'Kuta Baro',
                    'Kuta Cot Glie',
                    'Kuta Malaka',
                    'Lembah Seulawah',
                    'Leupung',
                    'Lhoong',
                    'Lhoknga',
                    'Mesjid Raya',
                    'Montasik',
                    'Peukan Bada',
                    'Pulo Aceh',
                    'Seulimeum',
                    'Simpang Tiga',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KAB. ACEH JAYA',
                'kecamatan' => [
                    'Teunom',
                    'Pasie Raya',
                    'Panga',
                    'Krueng Sabee',
                    'Setia Bakti',
                    'Sampoiniet',
                    'Darul Hikmah',
                    'Indra Jaya',
                    'Jaya (Lamno)',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KAB. ACEH SELATAN',
                'kecamatan' => [
                    'Bakongan',
                    'Bakongan Timur',
                    'Kluet Selatan',
                    'Kluet Tengah',
                    'Kluet Timur',
                    'Kluet Utara',
                    'Kota Bahagia',
                    'Labuhan Haji',
                    'Labuhan Haji Barat',
                    'Labuhan Haji Timur',
                    'Meukek',
                    'Pasie Raja',
                    'Sama Dua',
                    'Sawang',
                    'Tapaktuan',
                    'Trumon',
                    'Trumon Tengah',
                    'Trumon Timur',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KAB. ACEH SINGKIL',
                'kecamatan' => [
                    'Danau Paris',
                    'Gunung Meriah',
                    'Kota Baharu',
                    'Kuala Baru',
                    'Pulau Banyak',
                    'Pulau Banyak Barat',
                    'Simpang Kanan',
                    'Singkil',
                    'Singkil Utara',
                    'Singkohor',
                    'Suro Makmur',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KAB. ACEH TAMIANG',
                'kecamatan' => [
                    'Banda Mulia',
                    'Bendahara',
                    'Karang Baru',
                    'Kejuruan Muda',
                    'Kota Kuala Simpang',
                    'Manyak Payed',
                    'Rantau',
                    'Sekerak',
                    'Seruway',
                    'Tamiang Hulu',
                    'Tenggulun',
                    'Bandar Pusaka',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KAB. ACEH TENGAH',
                'kecamatan' => [
                    'Bebesen',
                    'Bies',
                    'Jagong Jeget',
                    'Kebayakan',
                    'Ketol',
                    'Kute Panang',
                    'Laut Tawar',
                    'Lingë',
                    'Pegasing',
                    'Rusip Antara',
                    'Silih Nara',
                    'Bintang',
                    'Celala',
                    'Atu Lintang',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KAB. ACEH TENGGARA',
                'kecamatan' => [
                    'Babussalam',
                    'Badar',
                    'Bambel',
                    'Babul Makmur',
                    'Babul Rahmah',
                    'Bukit Tusam',
                    'Darul Hasanah',
                    'Deleng Pokhisen',
                    'Ketambe',
                    'Kuala',
                    'Lawe Alas',
                    'Lawe Bulan',
                    'Lawe Sigala-Gala',
                    'Lawe Sumur',
                    'Leuser',
                    'Semadam',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KAB. ACEH TIMUR',
                'kecamatan' => [
                    'Banda Alam',
                    'Birem Bayeun',
                    'Darul Aman',
                    'Darul Falah',
                    'Darul Ihsan',
                    'Idi Rayeuk',
                    'Idi Timur',
                    'Idi Tunong',
                    'Indra Makmur',
                    'Julok',
                    'Madat',
                    'Nurussalam',
                    'Pante Bidari',
                    'Peudawa',
                    'Peunaron',
                    'Peureulak',
                    'Peureulak Barat',
                    'Peureulak Timur',
                    'Rantau Selamat',
                    'Rantau Peureulak',
                    'Serbajadi',
                    'Simpang Jernih',
                    'Simpang Ulim',
                    'Sungai Raya',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KAB. ACEH UTARA',
                'kecamatan' => [
                    'Baktiya',
                    'Baktiya Barat',
                    'Banda Baro',
                    'Cot Girek',
                    'Dewantara',
                    'Geuredong Pase',
                    'Kuta Makmur',
                    'Langkahan',
                    'Lapang',
                    'Lhoksukon',
                    'Matangkuli',
                    'Meurah Mulia',
                    'Muara Batu',
                    'Nibong',
                    'Nisam',
                    'Nisam Antara',
                    'Paya Bakong',
                    'Pirak Timu',
                    'Samudera',
                    'Sawang',
                    'Seunuddon',
                    'Simpang Keramat',
                    'Syamtalira Aron',
                    'Syamtalira Bayu',
                    'Tanah Jambo Aye',
                    'Tanah Luas',
                    'Tanah Pasir',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KAB. BENER MERIAH',
                'kecamatan' => [
                    'Bandar',
                    'Bener Kelipah',
                    'Bukit',
                    'Gajah Putih',
                    'Mesidah',
                    'Permata',
                    'Pintu Rime Gayo',
                    'Syiah Utama',
                    'Timang Gajah',
                    'Wih Pesam',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KAB. BIREUEN',
                'kecamatan' => [
                    'Ganda Pura',
                    'Jangka',
                    'Jeunieb',
                    'Juli',
                    'Kota Juang',
                    'Kuala',
                    'Kuta Blang',
                    'Makmur',
                    'Pandrah',
                    'Peudada',
                    'Peulimbang',
                    'Peusangan',
                    'Peusangan Selatan',
                    'Peusangan Siblah Krueng',
                    'Samalanga',
                    'Simpang Mamplam',
                    'Jeumpa',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KAB. GAYO LUES',
                'kecamatan' => [
                    'Blangkejeren',
                    'Blang Pegayon',
                    'Dabun Gelang',
                    'Kuta Panjang',
                    'Pantan Cuaca',
                    'Pining',
                    'Putri Betung',
                    'Rikit Gaib',
                    'Rikik',
                    'Terangun',
                    'Tripe Jaya',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KAB. NAGAN RAYA',
                'kecamatan' => [
                    'Beutong',
                    'Beutong Ateuh Banggalang',
                    'Darul Makmur',
                    'Kuala',
                    'Kuala Pesisir',
                    'Seunagan',
                    'Seunagan Timur',
                    'Suka Makmue',
                    'Tadu Raya',
                    'Tripa Makmur',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KAB. PIDIE',
                'kecamatan' => [
                    'Batee',
                    'Delima',
                    'Geumpang',
                    'Glumpang Baro',
                    'Glumpang Tiga',
                    'Grong-Grong',
                    'Indrajaya',
                    'Kembang Tanjong',
                    'Keumala',
                    'Kota Sigli',
                    'Mane',
                    'Mila',
                    'Muara Tiga',
                    'Mutiara',
                    'Mutiara Timur',
                    'Padang Tiji',
                    'Peukan Baro',
                    'Pidie',
                    'Sakti',
                    'Simpang Tiga',
                    'Tangse',
                    'Tiro/Truseb',
                    'Titeue',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KAB. PIDIE JAYA',
                'kecamatan' => [
                    'Bandar Baru',
                    'Bandar Dua',
                    'Jangka Buya',
                    'Meurah Dua',
                    'Meureudu',
                    'Panteraja',
                    'Trienggadeng',
                    'Ulim',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KAB. SIMEULUE',
                'kecamatan' => [
                    'Simeulue Barat',
                    'Simeulue Tengah',
                    'Simeulue Timur',
                    'Teupah Barat',
                    'Teupah Selatan',
                    'Teupah Tengah',
                    'Teluk Dalam',
                    'Alafan',
                    'Salang',
                    'Saling',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KOTA BANDA ACEH',
                'kecamatan' => [
                    'Baiturrahman',
                    'Banda Raya',
                    'Jaya Baru',
                    'Kuta Alam',
                    'Kuta Raja',
                    'Lueng Bata',
                    'Meuraxa',
                    'Syiah Kuala',
                    'Ulee Kareng',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KOTA LANGSA',
                'kecamatan' => [
                    'Langsa Barat',
                    'Langsa Kota',
                    'Langsa Lama',
                    'Langsa Timur',
                    'Langsa Tualang Cut',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KOTA LHOKSEUMAWE',
                'kecamatan' => [
                    'Banda Sakti',
                    'Blang Mangat',
                    'Muara Dua',
                    'Muara Satu',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KOTA SABANG',
                'kecamatan' => [
                    'Sukajaya',
                    'Sukakarya',
                    'Sukamakmue',
                ],
            ],
            [
                'id_provinsi' => 1,
                'nama_kota_kab' => 'KOTA SUBULUSSALAM',
                'kecamatan' => [
                    'Longkib',
                    'Penanggalan',
                    'Rundeng',
                    'Simpang Kiri',
                    'Sultan Daulat',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. ASAHAN',
                'kecamatan' => [
                    'Air Batu',
                    'Air Joman',
                    'Aek Kuasan',
                    'Aek Ledong',
                    'Bandar Pasir Mandoge',
                    'Bandar Pulau',
                    'Buntu Pane',
                    'Kisaran Barat',
                    'Kisaran Timur',
                    'Meranti',
                    'Meranti Paham',
                    'Pulau Rakyat',
                    'Pulo Bandring',
                    'Rahuning',
                    'Rawang Panca Arga',
                    'Sei Dadap',
                    'Sei Kepayang',
                    'Sei Kepayang Barat',
                    'Sei Kepayang Timur',
                    'Setia Janji',
                    'Silau Laut',
                    'Simpang Empat',
                    'Tanjung Balai',
                    'Tinggi Raja',
                    'Teluk Dalam',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. BATU BARA',
                'kecamatan' => [
                    'Air Putih',
                    'Datuk Lima Puluh',
                    'Datuk Tanah Datar',
                    'Laut Tador',
                    'Lima Puluh',
                    'Lima Puluh Pesisir',
                    'Medang Deras',
                    'Nibung Hangus',
                    'Sei Balai',
                    'Sei Suka',
                    'Tanjung Tiram',
                    'Talawi',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. DAIRI',
                'kecamatan' => [
                    'Berampu',
                    'Gunung Sitember',
                    'Lae Parira',
                    'Parbuluan',
                    'Pegagan Hilir',
                    'Sidikalang',
                    'Siempat Nempu',
                    'Siempat Nempu Hilir',
                    'Siempat Nempu Hulu',
                    'Silahi Sabungan',
                    'Silima Pungga-Pungga',
                    'Sumbul',
                    'Sitinjo',
                    'Tanah Pinem',
                    'Tiga Lingga',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. DEKI SERDANG',
                'kecamatan' => [
                    'Batang Kuis',
                    'Beringin',
                    'Biru-Biru',
                    'Bondar Meriah',
                    'Bangun Purba',
                    'Deli Tua',
                    'Galang',
                    'Gunung Meriah',
                    'Hamparan Perak',
                    'Kutalimbaru',
                    'Labuhan Deli',
                    'Lubuk Pakam',
                    'Namo Rambe',
                    'Pagar Merbau',
                    'Pantai Labu',
                    'Patumbak',
                    'Percut Sei Tuan',
                    'Sibolangit',
                    'Sinembah Tanjung Muda Hilir',
                    'Sinembah Tanjung Muda Hulu',
                    'Sunggal',
                    'Tanjung Morawa',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. HUMBANG HASUNDUTAN',
                'kecamatan' => [
                    'Bakti Raja',
                    'Dolok Sanggul',
                    'Lintong Nihuta',
                    'Onan Ganjang',
                    'Pakkat',
                    'Paranginan',
                    'Parlilitan',
                    'Pollung',
                    'Sijama Polang',
                    'Tara Bintang',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. KARO',
                'kecamatan' => [
                    'Barusjahe',
                    'Berastagi',
                    'Dolat Rayat',
                    'Juhar',
                    'Kabanjahe',
                    'Kuta Buluh',
                    'Laubaleng',
                    'Mardinding',
                    'Merdeka',
                    'Merek',
                    'Munte',
                    'Nama Teran',
                    'Payung',
                    'Simpang Empat',
                    'Tiga Binanga',
                    'Tiga Panah',
                    'Tiganderket',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. LABUHAN BATU',
                'kecamatan' => [
                    'Bilah Barat',
                    'Bilah Hilir',
                    'Bilah Hulu',
                    'Panai Hilir',
                    'Panai Hulu',
                    'Panai Tengah',
                    'Pangkatan',
                    'Rantau Selatan',
                    'Rantau Utara',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. LABUHANBATU SELATAN',
                'kecamatan' => [
                    'Kampung Rakyat',
                    'Kota Pinang',
                    'Sei Kanan',
                    'Silangkitang',
                    'Torgamba',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. LABUHANBATU UTARA',
                'kecamatan' => [
                    'Aek Kuo',
                    'Aek Natas',
                    'Kualuh Hilir',
                    'Kualuh Hulu',
                    'Kualuh Leidong',
                    'Kualuh Selatan',
                    'Marbau',
                    'Na IX-X',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. LANGKAT',
                'kecamatan' => [
                    'Bahorok',
                    'Batang Serangan',
                    'Besitang',
                    'Binjai',
                    'Brandan Barat',
                    'Gebang',
                    'Hinai',
                    'Kuala',
                    'Kutambaru',
                    'Padang Tualang',
                    'Pangkalan Susu',
                    'Pematang Jaya',
                    'Salapian',
                    'Sawit Seberang',
                    'Secanggang',
                    'Sei Bingei',
                    'Sei Lepan',
                    'Selesai',
                    'Sirapit',
                    'Stabat',
                    'Tanjung Pura',
                    'Wampu',
                    'Bahorok Hulu',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. MANDAILING NATAL',
                'kecamatan' => [
                    'Batahan',
                    'Batang Natal',
                    'Bukit Malintang',
                    'Huta Bargot',
                    'Kotanopan',
                    'Lembah Sorik Merapi',
                    'Lingga Bayu',
                    'Muara Batang Gadis',
                    'Muara Sipongi',
                    'Naga Juang',
                    'Natal',
                    'Pakantan',
                    'Panyabungan',
                    'Panyabungan Barat',
                    'Panyabungan Selatan',
                    'Panyabungan Timur',
                    'Panyabungan Utara',
                    'Puncak Sorik Marapi',
                    'Ranto Baek',
                    'Siabu',
                    'Sinunukan',
                    'Tambangan',
                    'Ulu Pungkut',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. NIAS',
                'kecamatan' => [
                    'Bawolato',
                    'Botomuzoi',
                    'Gido',
                    'Hili Serangkai',
                    'Hiliduho',
                    'Idanogawo',
                    'Ma’u',
                    'Sogae’adu',
                    'Somölö-Mölö',
                    'Ulugawo',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. NIAS BARAT',
                'kecamatan' => [
                    'Lahomi',
                    'Lolofitu Moi',
                    'Mandrehe',
                    'Mandrehe Barat',
                    'Mandrehe Utara',
                    'Moro’o',
                    'Sirombu',
                    'Ulu Moro’o',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. NIAS SELATAN',
                'kecamatan' => [
                    'Amandraya',
                    'Aramo',
                    'Boronadu',
                    'Fanayama',
                    'Gomo',
                    'Hibala',
                    'Hilimegai',
                    'Huruna',
                    'Idanotae',
                    'Lahusa',
                    'Lolomatua',
                    'Lolowau',
                    'Maniamolo',
                    'Mazino',
                    'Mazo',
                    'O’ou',
                    'Onohazumba',
                    'Pulau-Pulau Batu',
                    'Pulau-Pulau Batu Barat',
                    'Pulau-Pulau Batu Timur',
                    'Pulau-Pulau Batu Utara',
                    'Sidua’ori',
                    'Simuk',
                    'Somambawa',
                    'Susua',
                    'Tanah Masa',
                    'Teluk Dalam',
                    'Toma',
                    'Ulunoyo',
                    'Ulususua',
                    'Ulu Idanotae',
                    'Umbunasi',
                    'Huruna Selatan',
                    'Lahusa Timur',
                    'Hilimegai Timur',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. NIAS UTARA',
                'kecamatan' => [
                    'Afulu',
                    'Alasa',
                    'Alasa Talumuzoi',
                    'Lahewa',
                    'Lahewa Timur',
                    'Lotu',
                    'Namohalu Esiwa',
                    'Sawo',
                    'Sitolu Ori',
                    'Tugala Oyo',
                    'Tuhemberua',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. PADANG LAWAS',
                'kecamatan' => [
                    'Aek Nabara Barumun',
                    'Barumun',
                    'Barumun Baru',
                    'Barumun Selatan',
                    'Barumun Tengah',
                    'Batang Lubu Sutam',
                    'Hutaraja Tinggi',
                    'Lubuk Barumun',
                    'Sihapas Barumun',
                    'Sosa',
                    'Sosa Julu',
                    'Sosa Timur',
                    'Ulu Barumun',
                    'Ulu Sosa',
                    'Hutarimbaru',
                    'Sibuhuan',
                    'Barumun Barat',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. PADANG LAWAS UTARA',
                'kecamatan' => [
                    'Batang Onang',
                    'Dolok',
                    'Dolok Sigompulon',
                    'Halongonan',
                    'Halongonan Timur',
                    'Hulu Sihapas',
                    'Padang Bolak',
                    'Padang Bolak Julu',
                    'Portibi',
                    'Simangambat',
                    'Ujung Batu',
                    'Gunung Tua',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. PAKPAK BHARAT',
                'kecamatan' => [
                    'Kerajaan',
                    'Pagindar',
                    'Pergetteng-getteng Sengkut',
                    'Salak',
                    'Siempat Rube',
                    'Sitellu Tali Urang Jehe',
                    'Sitellu Tali Urang Julu',
                    'Tinada',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. SAMOSIR',
                'kecamatan' => [
                    'Harian',
                    'Nainggolan',
                    'Onan Runggu',
                    'Palipi',
                    'Pangururan',
                    'Ronggur Nihuta',
                    'Sianjur Mula-Mula',
                    'Simanindo',
                    'Sitio-tio',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. SERDANG BEDAGAI',
                'kecamatan' => [
                    'Bandar Khalifah',
                    'Bandar Masilam',
                    'Bintang Bayu',
                    'Dolok Masihul',
                    'Dolok Merawan',
                    'Kotarih',
                    'Pantai Cermin',
                    'Pegajahan',
                    'Perbaungan',
                    'Sei Bamban',
                    'Sei Rampah',
                    'Serba Jadi',
                    'Silinda',
                    'Sipispis',
                    'Tanjung Beringin',
                    'Tebing Syahbandar',
                    'Tebing Tinggi',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. SIMALUNGUN',
                'kecamatan' => [
                    'Bandar',
                    'Bandar Huluan',
                    'Bandar Masilam',
                    'Bosar Maligas',
                    'Dolok Batu Nanggar',
                    'Dolok Panribuan',
                    'Dolok Pardamean',
                    'Dolok Silau',
                    'Girsang Sipangan Bolon',
                    'Gunung Malela',
                    'Gunung Maligas',
                    'Haranggaol Horisan',
                    'Hatonduhan',
                    'Huta Bayu Raja',
                    'Jawa Maraja Bah Jambi',
                    'Jorlang Hataran',
                    'Panei',
                    'Panombeian Panei',
                    'Pematang Bandar',
                    'Pematang Sidamanik',
                    'Pematang Silima Huta',
                    'Purba',
                    'Raya',
                    'Raya Kahean',
                    'Siantar',
                    'Sidamanik',
                    'Silimakuta',
                    'Silou Kahean',
                    'Tanah Jawa',
                    'Tapian Dolok',
                    'Ujung Padang',
                    'Uray',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. TAPANULI SELATAN',
                'kecamatan' => [
                    'Angkola Barat',
                    'Angkola Sangkunur',
                    'Angkola Selatan',
                    'Angkola Timur',
                    'Angkola Muara Tais',
                    'Arse',
                    'Batang Angkola',
                    'Batang Toru',
                    'Marancar',
                    'Muara Batang Toru',
                    'Saipar Dolok Hole',
                    'Sayur Matinggi',
                    'Sipirok',
                    'Tano Tombangan Angkola',
                    'Aek Bilah',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. TAPANULI TENGAH',
                'kecamatan' => [
                    'Andam Dewi',
                    'Badiri',
                    'Barus',
                    'Barus Utara',
                    'Kolang',
                    'Lumut',
                    'Manduamas',
                    'Pandan',
                    'Pasaribu Tobing',
                    'Pinangsori',
                    'Sarudik',
                    'Sibabangun',
                    'Sirandorung',
                    'Sitahuis',
                    'Sorkam',
                    'Sorkam Barat',
                    'Sosorgadong',
                    'Suka Bangun',
                    'Tapian Nauli',
                    'Tukka',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. TAPANULI UTARA',
                'kecamatan' => [
                    'Adian Koting',
                    'Garoga',
                    'Muara',
                    'Pagaran',
                    'Pahae Jae',
                    'Pahae Julu',
                    'Pangaribuan',
                    'Parmonangan',
                    'Purbatua',
                    'Siatas Barita',
                    'Siborong-Borong',
                    'Sipahutar',
                    'Sipoholon',
                    'Tarutung',
                    'Simangumban',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KAB. TOBA',
                'kecamatan' => [
                    'Balige',
                    'Bonatua Lunasi',
                    'Borbor',
                    'Habinsaran',
                    'Laguboti',
                    'Lumban Julu',
                    'Nassau',
                    'Parmaksian',
                    'Pintu Pohan Meranti',
                    'Porsea',
                    'Siantar Narumonda',
                    'Sigumpar',
                    'Silaen',
                    'Tampahan',
                    'Uluan',
                    'Ajibata',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KOTA BINJAI',
                'kecamatan' => [
                    'Binjai Barat',
                    'Binjai Kota',
                    'Binjai Selatan',
                    'Binjai Timur',
                    'Binjai Utara',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KOTA GUNUNG SITOLI',
                'kecamatan' => [
                    'Gunungsitoli',
                    'Gunungsitoli Alo oa',
                    'Gunungsitoli Barat',
                    'Gunungsitoli Idanoi',
                    'Gunungsitoli Selatan',
                    'Gunungsitoli Utara',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KOTA MEDAN',
                'kecamatan' => [
                    'Medan Amplas',
                    'Medan Area',
                    'Medan Barat',
                    'Medan Baru',
                    'Medan Belawan',
                    'Medan Deli',
                    'Medan Denai',
                    'Medan Helvetia',
                    'Medan Johor',
                    'Medan Kota',
                    'Medan Labuhan',
                    'Medan Maimun',
                    'Medan Marelan',
                    'Medan Perjuangan',
                    'Medan Petisah',
                    'Medan Polonia',
                    'Medan Sunggal',
                    'Medan Selayang',
                    'Medan Tembung',
                    'Medan Timur',
                    'Medan Tuntungan',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KOTA PADANGSIDIMPUAN',
                'kecamatan' => [
                    'Padangsidimpuan Angkola Julu',
                    'Padangsidimpuan Batunadua',
                    'Padangsidimpuan Hutaimbaru',
                    'Padangsidimpuan Selatan',
                    'Padangsidimpuan Tenggara',
                    'Padangsidimpuan Utara',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KOTA PAMANGSIANTAR',
                'kecamatan' => [
                    'Siantar Barat',
                    'Siantar Marihat',
                    'Siantar Marihon',
                    'Siantar Martoba',
                    'Siantar Selatan',
                    'Siantar Sitalasari',
                    'Siantar Timur',
                    'Siantar Utara',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KOTA SIBOLGA',
                'kecamatan' => [
                    'Sibolga Kota',
                    'Sibolga Sambas',
                    'Sibolga Selatan',
                    'Sibolga Utara',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KOTA TANJUNGBALAI',
                'kecamatan' => [
                    'Datuk Bandar',
                    'Datuk Bandar Timur',
                    'Sei Tualang Raso',
                    'Tanjungbalai Selatan',
                    'Tanjungbalai Utara',
                    'Teluk Nibung',
                ],
            ],
            [
                'id_provinsi' => 2,
                'nama_kota_kab' => 'KOTA TEBINGTINGGI',
                'kecamatan' => [
                    'Bajenis',
                    'Padang Hilir',
                    'Padang Hulu',
                    'Rambutan',
                    'Tebing Tinggi Kota',
                ],
            ],

        ];

        foreach ($kotaKabList as $kotaIndex => $kotaData) {
            // Insert Kota/Kabupaten
            $idKotaKab = DB::table('kota_kabupatens')->insertGetId([
                'id_provinsi' => $kotaData['id_provinsi'],
                'nama_kota_kab' => $kotaData['nama_kota_kab'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            // Insert Kecamatan per Kota/Kabupaten
            $kecamatanData = [];
            foreach ($kotaData['kecamatan'] as $kecamatanName) {
                $kecamatanData[] = [
                    'nama_kecamatan' => $kecamatanName,
                    'id_kota_kabupaten' => $idKotaKab,
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            }

            DB::table('kecamatans')->insert($kecamatanData);
        }
    }
}
